import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

const jakartaSansFont = Plus_Jakarta_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Kanban App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jakartaSansFont.className}>{children}</body>
    </html>
  );
}
